let states = [
	{ id:'US-AK', name: 'Alaska' },
	{ id:'US-AL', name: 'Alabama' },
	{ id:'US-AR', name: 'Arkansas' },
	{ id:'US-AZ', name: 'Arizona' },
	{ id:'US-CA', name: 'California' },
	{ id:'US-CO', name: 'Colorado' },
	{ id:'US-CT', name: 'Connecticut' },
	{ id:'US-DC', name: 'District Of Columbia' },
	{ id:'US-DE', name: 'Delaware' },
	{ id:'US-FL', name: 'Florida' },
	{ id:'US-GA', name: 'Georgia' },
	{ id:'US-HI', name: 'Hawaii' },
	{ id:'US-IA', name: 'Iowa' },
	{ id:'US-ID', name: 'Idaho' },
	{ id:'US-IL', name: 'Illinois' },
	{ id:'US-IN', name: 'Indiana' },
	{ id:'US-KS', name: 'Kansas' },
	{ id:'US-KY', name: 'Kentucky' },
	{ id:'US-LA', name: 'Louisiana' },
	{ id:'US-MA', name: 'Massachusetts' },
	{ id:'US-MD', name: 'Maryland' },
	{ id:'US-ME', name: 'Maine' },
	{ id:'US-MI', name: 'Michigan' },
	{ id:'US-MN', name: 'Minnesota' },
	{ id:'US-MO', name: 'Missouri' },
	{ id:'US-MS', name: 'Mississippi' },
	{ id:'US-MT', name: 'Montana' },
	{ id:'US-NC', name: 'North Carolina' },
	{ id:'US-ND', name: 'North Dakota' },
	{ id:'US-NE', name: 'Nebraska' },
	{ id:'US-NH', name: 'New Hampshire' },
	{ id:'US-NJ', name: 'New Jersey' },
	{ id:'US-NM', name: 'New Mexico' },
	{ id:'US-NV', name: 'Nevada' },
	{ id:'US-NY', name: 'New York' },
	{ id:'US-OH', name: 'Ohio' },
	{ id:'US-OK', name: 'Oklahoma' },
	{ id:'US-OR', name: 'Oregon' },
	{ id:'US-PA', name: 'Pennsylvania' },
	{ id:'US-RI', name: 'Rhode Island' },
	{ id:'US-SC', name: 'South Carolina' },
	{ id:'US-SD', name: 'South Dakota' },
	{ id:'US-TN', name: 'Tennessee' },
	{ id:'US-TX', name: 'Texas' },
	{ id:'US-UT', name: 'Utah' },
	{ id:'US-VA', name: 'Virginia' },
	{ id:'US-VT', name: 'Vermont' },
	{ id:'US-WA', name: 'Washington' },
	{ id:'US-WI', name: 'Wisconsin' },
	{ id:'US-WV', name: 'West Virginia' },
	{ id:'US-WY', name: 'Wyoming' }
    ];
    
module.exports = states;